//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_ROLE
    {
        public int ID { get; set; }
        public Nullable<int> IDROLE { get; set; }
        public Nullable<int> IDUSER { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual LIST_ROLE LIST_ROLE { get; set; }
    }
}
