//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNALACCOUNT
    {
        public int IDUSER { get; set; }
        public string LOGINPROVIDER { get; set; }
        public string PROVIDERKEY { get; set; }
    }
}
